export enum CharacterId {
	Betilla = "Betilla",
	Bzzit = "Bzzit",
	Electoon = "Electoon",
	Joe = "Joe",
	Magician = "Magician",
	Medallion = "Medallion",
	MrDark = "MrDark",
	MrSax = "MrSax",
	MrSkops = "MrSkops",
	MrStone = "MrStone",
	Musician = "Musician",
	Painter = "Painter",
	Photographer = "Photographer",
	Rayman = "Rayman",
	SpaceMama = "SpaceMama",
	Tarayzan = "Tarayzan",
}
