import { MusicId } from "./identifiers/musicId";

export interface MusicData {
	url: string;
	extraVolume?: true;
}

export const musicDatabase: { [music in MusicId]: MusicData } = {
	MusicianSong: { url: "./assets/music/musician_song.mp3", extraVolume: true },
	AnimalLife: { url: "./assets/music/animal_life.mp3" },
	BetillaTheFairy: { url: "./assets/music/betilla_the_fairy.mp3" },
	BlazingBrass: { url: "./assets/music/blazing_brass.mp3" },
	BongoBridge: { url: "./assets/music/bongo_bridge.mp3" },
	BzzitAttacks: { url: "./assets/music/bzzit_attacks.mp3" },
	Cakewalk: { url: "./assets/music/cakewalk.mp3" },
	CallOfTheMountain: { url: "./assets/music/call_of_the_mountain.mp3" },
	CandyParty: { url: "./assets/music/candy_party.mp3" },
	CreepyClowns: { url: "./assets/music/creepy_clowns.mp3" },
	CuttingTheRopes: { url: "./assets/music/cutting_the_ropes.mp3" },
	DeepConcentration: { url: "./assets/music/deep_concentration.mp3" },
	DeepForest: { url: "./assets/music/deep_forest.mp3" },
	DizzyingHeights: { url: "./assets/music/dizzying_heights.mp3" },
	DrumsOfTheEnemy: { url: "./assets/music/drums_of_the_enemy.mp3" },
	DuetWithMrSax: { url: "./assets/music/duet_with_mr_sax.mp3" },
	EnteringTheCavern: { url: "./assets/music/entering_the_cavern.mp3" },
	FirstSteps: { url: "./assets/music/first_steps.mp3" },
	FlightOfTheMosquito: { url: "./assets/music/flight_of_the_mosquito.mp3" },
	Harmony: { url: "./assets/music/harmony.mp3" },
	HoldOnTight: { url: "./assets/music/hold_on_tight.mp3" },
	KingOfTheMountain: { url: "./assets/music/king_of_the_mountain.mp3" },
	LearningWithRayman: { url: "./assets/music/learning_with_rayman.mp3" },
	LurkingInTheDarkness: { url: "./assets/music/lurking_in_the_darkness.mp3" },
	MeditatingMonks: { url: "./assets/music/meditating_monks.mp3" },
	MoskitosRage: { url: "./assets/music/moskitos_rage.mp3" },
	MrDarksDare: { url: "./assets/music/mr_darks_dare.mp3" },
	NightOnBlueMountain: { url: "./assets/music/night_on_blue_mountain.mp3" },
	OnceMore: { url: "./assets/music/once_more.mp3" },
	PaintedPentathlon: { url: "./assets/music/painted_pentathlon.mp3" },
	PartyAtJoes: { url: "./assets/music/party_at_joes.mp3" },
	PeacefulPeaks: { url: "./assets/music/peaceful_peaks.mp3" },
	PicturePerfect: { url: "./assets/music/picture_perfect.mp3" },
	Rainfall: { url: "./assets/music/rainfall.mp3" },
	SoundsInTheShadows: { url: "./assets/music/sounds_in_the_shadows.mp3" },
	SpaceMamasFinale: { url: "./assets/music/space_mamas_finale.mp3" },
	SpaceMamasOverture: { url: "./assets/music/space_mamas_overture.mp3" },
	StageFright: { url: "./assets/music/stage_fright.mp3" },
	TheBandAwakens: { url: "./assets/music/the_band_awakens.mp3" },
	TheFlood: { url: "./assets/music/the_flood.mp3" },
	TheInkySea: { url: "./assets/music/the_inky_sea.mp3" },
	TheMagiciansChallenge: { url: "./assets/music/the_magicians_challenge.mp3" },
	TheMountainStreams: { url: "./assets/music/the_mountain_streams.mp3" },
	TheRedDrummers: { url: "./assets/music/the_red_drummers.mp3" },
	TheStalactitesTeardrops: { url: "./assets/music/the_stalactites_teardrops.mp3" },
	Thunderstorm: { url: "./assets/music/thunderstorm.mp3" },
	VenomousMrSkops: { url: "./assets/music/venomous_mr_skops.mp3" },
	WatchYourStep: { url: "./assets/music/watch_your_step.mp3" },
	WorldMap: { url: "./assets/music/world_map.mp3" },
};
